### ISSUE TITLE
Exception occurred in action '{"xpath":"//System.User[System.Session_User]"

### ISSUE THREAD

**Issue by Narev** [mendix/m2ee-tools#13]
We just upgrade to mx7 and when starting the m2ee tools we always get the below error. It looks as if it is the retrieve is somehow messed up.

`2017-07-27 14:26:52.974 ERROR - M2EE: com.mendix.m2ee.api.AdminException: An unhandled exception occurred!
        at com.mendix.m2ee.appcontainer.server.handler.HttpAdminHandler.handle(HttpAdminHandler.java:142)

Caused by: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"xpath":"//System.User[System.Session_User]","amount":-1,"depth
":0,"offset":-1,"sort":{},"type":"RetrieveXPathAction"}', all database changes executed by this action were rolled back
        at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.java:178)

Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"xpath":"//System.User[System.Session_User]","amount":-1,"depth":0,"offset":-1,"sort":{},"type":"Retr
ieveXPathAction"}', all database changes executed by this action were rolled back
        at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:37)

Caused by: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"xpath":"//System.User[System.Session_User]","amount":-1,"depth":0,"offset":-1,"sort":{},"type":"RetrieveXPathAction"}', all database changes executed by thi
s action were rolled back
        at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.processErrorState(CoreActionHandlerImpl.scala:152)

Caused by: com.mendix.basis.connectionbus.ConnectionBusException: An exception has occurred for the following request(s):
        InternalXPathTextGetRequest (depth = 0): //System.User[System.Session_User]
        at com.mendix.connectionbus.RequestAnalyzer.doRequest(RequestAnalyzer.java:49)

Caused by: com.mendix.basis.connectionbus.ConnectionBusException: Exception occurred while retrieving data. (SQL State: 42883, Error Code: 0)
        at com.mendix.connectionbus.connections.jdbc.JdbcDataStore.getCorrectException(JdbcDataStore.java:1010)

Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: bigint = boolean
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 611
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
`

**Comment by djvdorp** [comment]
I also noticed that this broke in Mendix 7 indeed!

**Comment by arjenw** [comment]
This has been fixed in [version 7.4](https://docs.mendix.com/releasenotes/desktop-modeler/7.4)
> We fixed the error that occurred while executing the get_logged_in_user_names admin action. (Ticket 52147)

**Comment by knorrie** [comment]
For m2ee-tools, this is not fixable, since the bug was not in here.

What would be possible is code version specific checks for the borken Mendix 7.x versions and then warn the user that the functionality is not usable. However, there's already enough special case handling code in the program, and I'm not going to do that.
