### ISSUE TITLE
Cannot run 2 mendix apps on linux 

### ISSUE THREAD

**Issue by Dungnt19** [mendix/m2ee-tools#64]
I have install m2ee-Tools  on debian and centos7 (non-root install) but when I add second application, it will run into java error.

How can I run 2 mendix apps on a *nix server

**Comment by hvisage** [comment]
(1) What is the Java errors?
(2) you did make sure they are on different ports or IPs?

**Comment by dungnt1989** [comment]
(1) this is the error log:
# on Centos 7
m2ee(mxappr): start
INFO: Trying to start the MxRuntime...
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.lang.reflect.Array.getLength(Native Method)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1320)
        at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$.com$mendix$container$deployment$internal$Interpreters$ClassLoaders$$delete$1(Interpreters.scala:78)
        at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$$anon$1.$anonfun$config$3(Interpreters.scala:91)
        at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$$anon$1.$anonfun$config$3$adapted(Interpreters.scala:91)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$$anon$1.<init>(Interpreters.scala:91)
        at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$.createClassloader(Interpreters.scala:83)
        at com.mendix.container.deployment.internal.Interpreters$ClassLoaders$.$anonfun$newDependency$1(Interpreters.scala:145)
        at cats.data.StateFunctions.$anonfun$modify$4(IndexedStateT.scala:363)
        at cats.data.StateFunctions.$anonfun$apply$2(IndexedStateT.scala:348)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at cats.data.AndThen.loop$1(AndThen.scala:107)
        at cats.data.AndThen.runLoop(AndThen.scala:116)
        at cats.data.AndThen.apply(AndThen.scala:68)
        at cats.data.IndexedStateT.$anonfun$run$1(IndexedStateT.scala:64)
        at cats.Eval$.loop$1(Eval.scala:358)
        at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363)
        at cats.Eval$FlatMap.value(Eval.scala:284)
        at com.mendix.container.deployment.Runners$.runClassloadersHierarchyBuilder(Runners.scala:111)
        at com.mendix.container.componentregistry.internal.ClassloaderComponentReader$.buildHierarchy(ClassloaderComponentReader.scala:214)
        at com.mendix.container.componentregistry.internal.ClassloaderComponentReader$.read(ClassloaderComponentReader.scala:22)
        at com.mendix.container.componentregistry.ComponentRegistry$.run(ComponentRegistry.scala:16)
        at com.mendix.container.boot.Container$.doStart(Container.scala:110)
        at com.mendix.container.boot.Container$.doStart(Container.scala:93)
        at com.mendix.container.boot.Container$.$anonfun$startAndWaitForever$2(Container.scala:70)
        at scala.util.Either.flatMap(Either.scala:352)
        at com.mendix.container.boot.Container$.$anonfun$startAndWaitForever$1(Container.scala:69)
        at com.mendix.container.boot.Container$.time(Container.scala:157)
        at com.mendix.container.boot.Container$.startAndWaitForever(Container.scala:69)
        at com.mendix.container.boot.Main$.$anonfun$new$2(Main.scala:14)
        at scala.util.Either.flatMap(Either.scala:352)
        at com.mendix.container.boot.Main$.delayedEndpoint$com$mendix$container$boot$Main$1(Main.scala:13)
        at com.mendix.container.boot.Main$delayedInit$body.apply(Main.scala:10)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.mendix.container.boot.Main$.main(Main.scala:10)
        at com.mendix.container.boot.Main.main(Main.scala)
ERROR: JVM process terminated without reason., errno: 0xa, subprocess output available

# On debian:
m2ee(mxhc): start
INFO: Trying to start the MxRuntime...
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
ERROR: JVM process terminated without reason., errno: 0xa, subprocess output available

(2)I'm sure  2 apps run on different ports.

**Comment by hvisage** [comment]
hmmm... double check the adminports are also different
